apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: iam-pam
data:
  init.sql: |
    -- Create Keycloak database
    CREATE DATABASE keycloak
        WITH
        OWNER = postgres
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.utf8'
        LC_CTYPE = 'en_US.utf8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;

    -- Create IAM/PAM application database
    CREATE DATABASE iam_pam_db
        WITH
        OWNER = postgres
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.utf8'
        LC_CTYPE = 'en_US.utf8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;

    \c iam_pam_db;

    CREATE SCHEMA IF NOT EXISTS shared;
    CREATE SCHEMA IF NOT EXISTS tenant_bank_a;
    CREATE SCHEMA IF NOT EXISTS tenant_bank_b;
    CREATE SCHEMA IF NOT EXISTS tenant_fintech_c;

    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
