package com.iam.pam.controller;

import com.iam.pam.dto.ApiResponse;
import com.iam.pam.dto.MfaDTO;
import com.iam.pam.service.MfaService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/user/mfa")
public class MfaController {

    private final MfaService mfaService;

    public MfaController(MfaService mfaService) { this.mfaService = mfaService; }

    // ── Tenant-admin: configure enabled methods ──────────────────────────────

    @GetMapping("/tenant-config")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<MfaDTO.TenantConfigResponse>> getTenantConfig() {
        return ResponseEntity.ok(ApiResponse.success(mfaService.getTenantConfig()));
    }

    @PutMapping("/tenant-config")
    @PreAuthorize("hasRole('tenant-admin')")
    public ResponseEntity<ApiResponse<MfaDTO.TenantConfigResponse>> updateTenantConfig(
            @Valid @RequestBody MfaDTO.TenantConfigRequest req) {
        return ResponseEntity.ok(ApiResponse.success(mfaService.updateTenantConfig(req)));
    }

    // ── User: enrollment ─────────────────────────────────────────────────────

    @GetMapping("/status")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<MfaDTO.StatusResponse>> getStatus(
            @AuthenticationPrincipal Jwt jwt) {
        String username = jwt.getClaimAsString("preferred_username");
        return ResponseEntity.ok(ApiResponse.success(mfaService.getStatus(username)));
    }

    /** Step 1 of enrollment — returns TOTP QR URI or sends OTP for email/SMS. */
    @PostMapping("/enroll/init")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<MfaDTO.InitEnrollResponse>> initEnroll(
            @AuthenticationPrincipal Jwt jwt,
            @Valid @RequestBody MfaDTO.InitEnrollRequest req) {
        String username = jwt.getClaimAsString("preferred_username");
        return ResponseEntity.ok(ApiResponse.success(mfaService.initEnroll(username, req)));
    }

    /** Step 2 of enrollment — confirms with OTP/TOTP code to activate. */
    @PostMapping("/enroll/confirm")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<String>> confirmEnroll(
            @AuthenticationPrincipal Jwt jwt,
            @Valid @RequestBody MfaDTO.ConfirmEnrollRequest req) {
        String username = jwt.getClaimAsString("preferred_username");
        mfaService.confirmEnroll(username, req);
        return ResponseEntity.ok(ApiResponse.success("MFA activé avec succès."));
    }

    @DeleteMapping("/enroll")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<String>> removeEnrollment(
            @AuthenticationPrincipal Jwt jwt) {
        String username = jwt.getClaimAsString("preferred_username");
        mfaService.removeEnrollment(username);
        return ResponseEntity.ok(ApiResponse.success("MFA supprimé."));
    }

    // ── Post-login MFA verification ──────────────────────────────────────────

    /** Sends (or re-sends) OTP for EMAIL/SMS. No-op for TOTP (code generated by app). */
    @PostMapping("/send-otp")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<MfaDTO.SendOtpResponse>> sendOtp(
            @AuthenticationPrincipal Jwt jwt) {
        String username = jwt.getClaimAsString("preferred_username");
        return ResponseEntity.ok(ApiResponse.success(mfaService.sendVerificationOtp(username)));
    }

    @PostMapping("/verify")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ApiResponse<MfaDTO.VerifyResponse>> verify(
            @AuthenticationPrincipal Jwt jwt,
            @Valid @RequestBody MfaDTO.VerifyRequest req) {
        String username = jwt.getClaimAsString("preferred_username");
        return ResponseEntity.ok(ApiResponse.success(mfaService.verifyMfa(username, req)));
    }
}
